app = "history-api"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
web = "python app.py"

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["web"]

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443