app = "history-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "true"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "python refresh_data.py"

[processes]
  refresh = "python refresh_data.py"
  web = "gunicorn app:app --bind 0.0.0.0:8080 --workers 2"